### ISSUE TITLE
Add ability to toggle individual blocks on and off

### ISSUE THREAD

**Issue by crimsonknave** [constantcontact/jenkins_pipeline_builder#38]
This is useful because for example, you might have a file to trigger a remote job, but sometimes you want it to poll, sometimes you want it to take parameters from a file and so on. But, the rest of the job is the same. This way you can pass in variables that will turn off sections of the yaml.

Without a toggle.

``` yaml
builders:
  - maven3:
    goals: -B clean
    rootPom: path_to_pom
    mavenName: maven-name # Optional
```

With a toggle. Everything inside parameters will be used just like they were directly beneath maven3.

``` yaml
builders:
  - maven3:
    enabled: true/false
    parameters:
      goals: -B clean
      rootPom: path_to_pom
      mavenName: maven-name # Optional
```
