### ISSUE TITLE
Can't turn off Jenkins tagging

### ISSUE THREAD

**Issue by robpark** [constantcontact/jenkins_pipeline_builder#48]
If I add the option manually, I get <hudson.plugins.git.extensions.impl.PerBuildTag/> in my config.
When I remove it (which is what I want, because it doesn't generate an extra tag), that element is simply removed. 

If I use
````
    scm_params:
        remote_name: origin
        excluded_users: 'jenkins'
        local_branch: 'master'
        skip_tag: true
````
I get this error:
````
ERROR -- : Extension scm_params does not support parameter skip_tag
````

If I remove skip_tag: true it will generate, but the xml has <skipTag>false</skipTag> now (which I can't get with just the UI) and no PerBuildTag element. However it gives me a second tag with the build name.
