### ISSUE TITLE
dependencies folder improvements

### ISSUE THREAD

**Issue by AndrewHanes** [constantcontact/jenkins_pipeline_builder#58]
Currently, to specify a dependency source that isn't in the root of a git repo I need to do this:

```yaml
- dependencies:
    - source:
        url: 'https://github.com/constantcontact/jenkins_pipeline_builder/archive/master.tar.gz'
        templates:
            - name: generator-template
              version: 1
              folder: 'example/example-templates/job-template/1' 
```

There should be another field, in the `source: ` hash, that allows a different template root directory to be defined.  This will allow us to access specific template versions and generally be cleaner.  Something like this:

```yaml
- dependencies:
    - source:
        url: 'https://github.com/constantcontact/jenkins_pipeline_builder/archive/master.tar.gz'
        template_root: 'example-templates/'
        templates:
            - name: generator-template
              version: 1
```
