### ISSUE TITLE
Add inheritance/overrides to jobs

### ISSUE THREAD

**Issue by crimsonknave** [constantcontact/jenkins_pipeline_builder#84]
In order to let people DRY things, we should have a way to inherit and/or override settings on a job.

To do this properly, we will need to come up with a way to override a single builder instead of having to override all of the builders since it's an array.

```yaml
- job:
    name: 'New-{{name}}-Commit'
    base_job: '{{name}}-Commit'
    overrides:
      builders:
        1: shell_command: 'new command'
```
